{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ctr-inference.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ctr-inference.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ctr-inference.selectorLabels" . | nindent 6 }}
      component: app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: api-consumer
      ports:
        - protocol: TCP
          port: 8000
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8001
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "ctr-inference.selectorLabels" . | nindent 14 }}
              component: triton
      ports:
        - protocol: TCP
          port: 8001
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
