apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctr-inference.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ctr-inference.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.secrets.apiKey | quote }}
  {{- if .Values.secrets.tritonAuthToken }}
  triton-auth-token: {{ .Values.secrets.tritonAuthToken | quote }}
  {{- end }}
